name: cross-compile dintwm

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.commits[0].message, '[build]')"
    container:
      image: docker.pkg.github.com/rasmusedgar/dintwm/dintwmbuild:latest
      credentials:
        username: rasmusedgar
        password: ${{ secrets.EDGAR_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Build dintwm
        run: make all
